### ISSUE TITLE
PointerEvent and drawing bug

### ISSUE THREAD

**Issue by bobosette** [RomanBase/hand_signature#10]
Hello. Let me congrat with you for this work, It's a really useful package. Thank you. 
But I noticed two issue:
1 Is there a way to get from the control some other infos like tilt, pressure, distance (these can be retreived with PointerEvent)?
2 When you first touch the display with the pen/hand, draw a very small path, then you get off the pen/hand from the display, and keep going like this, it seems difficult for the painter to draw these minipaths with precision. I don't know how to explain, I hope you have understood. Maybe I can fix this issue be increasing the velocity property??

**Comment by RomanBase** [comment]
Hi,

1. Currently no. Because library is focused primary to Signature drawing.. and pressure is not so relevant in this scenario. Mostly you just 'swing' your signature without any pressure, so velocity based line width is more useful.

2. You can adjust ``threshold`` - it controls minimal distance between two points. So with lower threshold you will receive more control points.

**Comment by RomanBase** [comment]
A little note to 2nd point:

Library uses ``PanGestureRecognizer`` to handle ``PointerEvents`` and this gesture recognizer has input lag before 'drag' starts. Thats the reason why really small lines can't be drawn.

On **devel** branch you can find version with custom and very simple ``GestureRecognizer``, But this implementation is still in very early version and without any testing..

**Comment by bobosette** [comment]
Just tried! It works fine. Tomorrow I'll make more tests but there are no more lags.
