### ISSUE TITLE
Playback animation of drawing progress?

### ISSUE THREAD

**Issue by jtkeyva** [RomanBase/hand_signature#11]
Cool package, and [story_painter](https://github.com/furkansarihan/story_painter) made it even closer to my needs.

Any chance it could "record" the paths as you draw them and then play them back as an animation?

Thanks

**Comment by RomanBase** [comment]
Hi, short answer is NO :) Just because this package is focused to hand signatures..

In fact it's theoretically possible, because path is recorded - every control point has timestamp. And it's possible to iterate thru every part separately. But you must create your ``CustomPainter`` to handle animation progress.

**Comment by jtkeyva** [comment]
Got it thanks. Maybe story_painter will implement at some point. Their undo function does a lot of the heavy lifting. If i can figure it out i'll share it at story_painter
