### ISSUE TITLE
Save and modify

### ISSUE THREAD

**Issue by bobosette** [RomanBase/hand_signature#15]
Hi. I know I can export the signature to svg and png, but is there a way to save the draw, then reopen and modify it?? Like for example the Samsung notes app

Thank you

**Comment by RomanBase** [comment]
Hi, it depends where you want to modify it ?
You can always export raw vector data ``HandSignatureControl.paths`` and do what ever you want with them :)

But currently there is no editor feature.. just because this package is meant to be used only for hand signatures (and typically you don't need to edit/adjust them).

**Comment by bobosette** [comment]
So you mean that if i save the paths, and then I reopen them it should be
possible to modify the draw, right?

Il Ven 21 Mag 2021, 14:24 Roman Hornak ***@***.***> ha
scritto:

**Comment by RomanBase** [comment]
Nope. You need to process editing in other lib or app.
This library doesn't support any type of editing...
