### ISSUE TITLE
HandSignature inside ListView

### ISSUE THREAD

**Issue by aarajput** [RomanBase/hand_signature#43]
If you please HandSignature widget inside ListVew and user tried to make a signature, list also move up and down with it.

**Comment by RomanBase** [comment]
Hey, by design it's not possible to use 'drawing' Widget inside any ScrollView. But you can solve this issue with little workaround - please check [scroll_test](https://github.com/RomanBase/hand_signature/blob/master/example/lib/scroll_test.dart) in example.

Basically you need to prevent ScrollView from receiving gesture events - there is multiple ways how to achieve this (`Focus`, `Listener`, `IgnorePointer`, `GestureDetector` etc) based on your needs.
In example you can find disabling scroll physics with `NeverScrollableScrollPhysics` on pointer down event.

Please check also similar issues: [#38](https://github.com/RomanBase/hand_signature/issues/38), [#2](https://github.com/RomanBase/hand_signature/issues/2)

**Comment by aarajput** [comment]
Here is how i fixed this issue.
I just wrapped HandSignature widget with GestureDetector widget and passed onHorizontalDragUpdate and onVerticalDragUpdate with empty function.

Example:
```
GestureDetector(
              onHorizontalDragUpdate: (_) {},
              onVerticalDragUpdate: (_) {},
              child: HandSignature(
                control: controller,
                color: Colors.black,
          ),
)
```

@RomanBase , i think you sould add this login in _example/lib/scroll_test.dart_

**Comment by RomanBase** [comment]
Hey, as mentioned above there is multiple solutions and every app will have other challenges to achieve correct behavior.
I think you solution (not tested) will not work inside PageView, because you override 'drag' events.
So in example is most general solution (maybe not correct for every Scrollable) that works as a 'hint' how to achieve something like this.

For example in our production code we mostly uses Overlay so 'Drawing Pad' is above Scrollable.

**Comment by loonix** [comment]
> Here is how i fixed this issue. I just wrapped HandSignature widget with GestureDetector widget and passed onHorizontalDragUpdate and onVerticalDragUpdate with empty function.
> 
> Example:
> 
> ```
> GestureDetector(
>               onHorizontalDragUpdate: (_) {},
>               onVerticalDragUpdate: (_) {},
>               child: HandSignature(
>                 control: controller,
>                 color: Colors.black,
>           ),
> )
> ```
> 
> [@RomanBase](https://github.com/RomanBase) , i think you sould add this login in _example/lib/scroll_test.dart_

this is brilliant, thanks
